#!/bin/sh

## This file generates all the packages and moves them
## to the dist/ directory.  It creates a tarball of the
## HTML documentation and gzips the BigHTML file.
## It also creates the PDF file, but does not compress
## it.
##
## It's intended use is to create an 'official' repository
## and be called via a cron job to update the docs for
## download.  It keeps all generated documentation, just
## copies it (sometimes compressed) to the dist/ directory

./gen clean

mkdir dist

# Generate html documentation
./gen html
cd html
tar -cz * > ../dist/html.tar.gz

## Generate bightml documentation
cd ..
./gen bightml
gzip manual.html
mv manual.html.gz dist/

# Generate PDF documentation
./gen pdf
cp manual.pdf dist/ 
