generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Item
    theme:            default
    list:
      display:        [Name, Path, hasChildren, parent_id, isAlbum]
      object_actions:
        _edit:
          name:       Edit image properties
