GALLERYDIR ?= ../../..
TOOLDIR ?= $(GALLERYDIR)/lib/tools

# The core module handles translations for the main gallery
# templates.  No other module or theme needs this.
#
EXTRA_DIR = ../../../templates

include $(TOOLDIR)/po/GNUmakefile.inc

